### ISSUE TITLE
Client state synchronization

### ISSUE THREAD

**Issue by Elyniss** [WalletConnect/walletconnect#56]
Any update should be pending until acknowledged

**Status**

Updated in:

- [x] JS
- [x] Swift
- [x] Kotlin

**Comment by llbartekll** [comment]
Peer should always have synchronised namespaces.

In order to achieve this, controller needs to persist unacknowledged namespaces in a temporary storage before accepting new state as a source of truth.

Namespaces can be upgraded only on acknowledgement of states that has been requested after last state update(current source of truth). Timestamps can be derived from request id.

**Comment by arein** [comment]
What does "client state synchronization" mean? :)
Curious to learn more. It's interesting for the backend as well for maybe disaster recovery
